<?php
$products = $this->getTopProducts();
if($products->getSize()) {
    ?>
    <div class="widget widget-viewed">
        <div class="block block-products">
            <div class="block-title">
                <strong><span><?php echo $this->__($this->_title) ?></span></strong>
            </div>
            <div class="block-content">
                <ol class="mini-products-list">
                    <?php foreach ($products as $product):
                        ?>
                        <li class="item">
                            <a class="product-image" href="<?php echo $product->getUrlPath() ?>" title="<?php echo $this->stripTags($product->getName(), null, true) ?>"><img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(50) ?>" width="50" height="50" alt="<?php echo $this->stripTags($product->getName(), null, true) ?>" /></a>
                            <div class="product-details">
                                <p class="product-name"><a href="<?php echo $product->getUrlPath() ?>" title="<?php echo $this->stripTags($product->getName(), null, true) ?>"><?php echo $this->helper('catalog/output')->productAttribute($product, $product->getName() , 'name') ?></a></p>
                            </div>
                        </li>
                    <?php endforeach; ?>
                </ol>
            </div>
        </div>
    </div>
    <?php
}
